### ISSUE TITLE
Request: return face neighbors of non-local cells

### ISSUE THREAD

**Issue by markusbattarbee** [fmihpc/dccrg#14]
For Vlasiator, it would be useful to be able to evaluate face neighbors of non-local cells as well, e.g. in the innermost row of ghost cells.

Could get_face_neighbors_of() be changed to return also these? It should be enough to remove the locality check.

**Comment by iljah** [comment]
I guess it should work, if you remove `this->cell_data.count(cell) == 0` check does it seem to work? :)
If neighborhood is large enough this should even return all face neighbors of some remote cells.

**Comment by markusbattarbee** [comment]
Yep, that's how I've been testing it. I'd just like to be able to compile against the proper master version, not a slightly edited one :)
If you want to keep the check in, it could perhaps be behind a boolean argument check, so I can turn it off for this purpose?

Also, I might need access to face neighbors with non-standard neighborhoods soon... :)

**Comment by iljah** [comment]
Cool, I'll try to come up with couple of simple tests for this. It did occur that boolean flag with default value of disallowing remote cells wouldn't break existing api but neither would adding support for remote cells. I'll probably just remove the check once I have basic tests for this.

For face neighbors with other neighborhoods you can check things manually as e.g. advection test solver does: https://github.com/fmihpc/dccrg/blob/master/tests/advection/solve.hpp#L73
Eventually I'll probably change get_face_neighbors() to work like that anyway which should also trivially support non-default neighborhoods.

**Comment by iljah** [comment]
Should be fixed by https://github.com/fmihpc/dccrg/commit/b5ecae24dd96e36c4e416b0f054dbd6afe566560
