### ISSUE TITLE
invalid initialization of reference of type ‘const dccrg

### ISSUE THREAD

**Issue by akbwyfc** [fmihpc/dccrg#25]
Hi All,

Thanks for sharing the code to the public.
In making Vlasiator I receive this error, I guess it is due to dccrg:

grid.cpp: In function ‘void updateRemoteVelocityBlockLists(dccrg::Dccrg<spatial_cell::SpatialCell, dccrg::Cartesian_Geometry>&, uint, uint)’:
grid.cpp:834:40: error: invalid initialization of reference of type ‘const dccrg::Dccrg<spatial_cell::SpatialCell, dccrg::Cartesian_Geometry>::Iterator_Storage<dccrg::Dccrg<spatial_cell::SpatialCell, dccrg::Cartesian_Geometry>::Cells_Item>& (dccrg::Dccrg<spatial_cell::SpatialCell, dccrg::Cartesian_Geometry>::*&&)(int) const’ from expression of type ‘<unresolved overloaded function type>’
  834 |         for (const auto& cell: mpiGrid.local_cells) {

I would be thankful for your helping me to build the code.

Cheers

**Comment by iljah** [comment]
Looks like this issue is with vlasiator not dccrg

**Comment by iljah** [comment]
Also they use https://github.com/fmihpc/dccrg/tree/vlasiator-version instead of mainline I believe

**Comment by akbwyfc** [comment]
Thanks @iljah, I tried with vlasiator-version and it compiled now.
