### ISSUE TITLE
Intel compiler is not able to compile dccrg application

### ISSUE THREAD

**Issue by galfthan** [fmihpc/dccrg#3]
When compiling vlasiator with icpc 15.0.2.164 on Sisu (Cray XC40), the compilation fails with a number of these kinds of errors:

```
In file included from /homeappl/home/alfthan/libraries/dccrg/dccrg_mapping.hpp(29),
                 from /homeappl/home/alfthan/libraries/dccrg/dccrg_no_geometry.hpp(33),
                 from /homeappl/home/alfthan/libraries/dccrg/dccrg.hpp(67),
                 from projects/KHB/../projects_common.h(11),
                 from projects/KHB/../project.h(4),
                 from projects/KHB/KHB.h(25),
                 from projects/KHB/KHB.cpp(27):
/homeappl/home/alfthan/libraries/dccrg/dccrg_mpi_support.hpp(365): error: class "std::unordered_map<int, MPI_Request={int}, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<const int, MPI_Request={int}>>>" has no member "at"
  			if (MPI_Wait(&(send_requests.at(process)), MPI_STATUS_IGNORE) != MPI_SUCCESS) {
``` 

The flags were -O2 -std=c++11 -openmp   -ansi-alias  so c++11 should be supported.

**Comment by galfthan** [comment]
It seems like the intel compiler relies on gcc for various c++ bits and pieces, at least parts of the std library are provided by gcc. The problem on the cray was that the default gcc was very old (4.3), with these modules this problem is avoided:

```
module swap PrgEnv-cray PrgEnv-intel
module swap intel intel/15.0.2.164 
module load gcc/4.9.2
```

**Comment by iljah** [comment]
> When compiling vlasiator with icpc 15.0.2.164 on Sisu (Cray XC40), the
> compilation fails with a number of these kinds of errors:
> |In file included from /homeappl/home/alfthan/libraries/dccrg/dccrg_mapping.hpp(29),
>                   from /homeappl/home/alfthan/libraries/dccrg/dccrg_no_geometry.hpp(33),
>                   from /homeappl/home/alfthan/libraries/dccrg/dccrg.hpp(67),
>                   from projects/KHB/../projects_common.h(11),
>                   from projects/KHB/../project.h(4),
>                   from projects/KHB/KHB.h(25),
>                   from projects/KHB/KHB.cpp(27):
> /homeappl/home/alfthan/libraries/dccrg/dccrg_mpi_support.hpp(365): error: class "std::unordered_map<int, MPI_Request={int}, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<const int, MPI_Request={int}>>>" has no member "at"
>              if (MPI_Wait(&(send_requests.at(process)), MPI_STATUS_IGNORE) != MPI_SUCCESS) {
> |
> The flags were -O2 -std=c++11 -openmp -ansi-alias so c++11 should be
> supported.

Hmm I think I've have compiled with intel 15.0.* several times without 
errors. The error seems quite weird, does something like this compile as 
that's what the error seems to be telling?

#include "unordered_map"
#include "mpi.h"
using namespace std;
int main() {
	unordered_map<int, MPI_Request> m;
	m.at(0);
	return 0;
}

Or can you reproduce in voima?

**Comment by iljah** [comment]
> It seems like the intel compiler relies on gcc for various c++ bits and
> pieces, at least parts of the std library are provided by gcc. The
> problem on the cray was that the default gcc was very old (4.3), with
> these modules this problem is avoided:
> |module swap PrgEnv-cray PrgEnv-intel
> module swap intel intel/15.0.2.164
> module load gcc/4.9.2
> |

Yeah I've had my share of weird errors from interactions between clang 
and gcc. I think it's something related to standard c++ library which 
can be provided, or not, by each compiler and in either case I guess 
they default to using the one in gcc or something.
